# Site Settings
title: "Jarret Angbazo - Data Scientist"
email: jarretangbazo@gmail.com
description: "Data Scientist specializing in Energy & Infrastructure Finance in Africa"
baseurl: ""
url: "https://jarretangbazo.github.io"
github_username: jarretangbazo
linkedin_username: jarretangbazo

# Build Settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Custom Settings
author: "Jarret Angbazo"

# Google Analytics
google_analytics: G-HHSXHBKKSE

# Navigation
#header_pages:
#  - about.md
#  - portfolio.md
#  - blog.md
#  - resume.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - docker-compose.yml
  - archive