services:
  jekyll:
    image: jekyll/jekyll:latest
    platform: linux/amd64
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
    command: jekyll serve --force_polling --livereload --drafts
